tool.html
I figured out what was the problem which was restricting the GIF to play in my browser. I will let you know once we meet tomorrow for further work.
=> Removed the dots

tool.html
Change the template file to have external style classes instead of inline styles.
=> Follow-up of commit - https://goo.gl/w7DDym

tool.css
The issue has been resolved. The heading now appears well with respect to the dark background. Do have a look. Thanks
=> Heading color changed

tool.css
Do check the size if it's ok or not.
=> Entropy visibility fixed

tool.css
You may now merge it after testing as I have changed the name. 
Thanks
=> class name changed

tool.css
PR#35 link - https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/35
=> Stylesheet corresponding to Pull#35

tool.html
Issue link - https://github.com/gbelwariar/Microbiome-Diversity-Inspector/issues/32
=> Fix Issue#32

server.js
This is a continuation of https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/39
The server fetches the list of organisms by sending an AJAX request to One Codex URL endpoint.
=> Add route for computing alpha diversity in the server.

client.js
1) Provide the client-side code corresponding to this PR - https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/39 &
https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/40
2) Follow Google JS style guide.
3) Send the request to the server for alpha-diversity computation.
4) Show alpha-diversity and loading graphics back to the user.
5) Provide ability to the 'Compute alpha-diversity' card to expand when the samples are loaded.
Note that to obtain the list of samples, an AJAX request to One Codex REST API is made in the client itself since it is expected to get the response quickly.
=> This commit does the following things- 

tool.html
@MAZHARMIK - Let me know if the below layout looks good to you.
=> Add card in the template to compute alpha-diversity.

tool.html
Do check it if it works properly. Due to some issue, it's not working in my laptop. 
I have tried to adjust the position of the analysis graph.
=> Adjusting the position of graph.

tool.css
This is a continuation of https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/49
=> Update stylesheet with the new path for the moved animation.

tool.html
1) Make the input boxes more flexible by enabling them to accept input strings with leading and trailing spaces.
2) Change the path to resources since now they are moved to their own directory in the below PRs - 
a) https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/49
b) https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/50
c) https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/51
=> This commit does the following things -

tool.css
As our web-app consists of one full page but not multiple pages, so I feel there should be division within the page to make it look bit better . Need your opinion on that.
=> Divider in the  page

tool.css, tool.html
This PR solves the following problems - 
1) Now the page size is not dependent on the number of files fetched from One Codex (as uploaded on One Codex server by the user).
2) Fix the huge "unwanted" stretch in the background DNA animation when showing the table.
Screenshot -
=> Add inner scroller to the table in the tool.

tool.css, tool.html
@MAZHARMIK  - Let me know if this looks good to you, otherwise I will revert back this change.
The UI of the tool now looks like below (as in Google Chrome) -
=> Add bouncing arrow to point the user towards the tool's features at the bottom of the page.

tool.html
PRs have been  merged an issues have been fixed. Do have a look. Thanks
=> Issues fixed

README.md
1) Add Prof. Malay Bhattacharyya to the list of contributors.
2) Add detailed instructions to install the web-based platform and the desktop-standalone application.
3) Add missing links to the technologies used.
=> This PR does the following things -

README.md
Do let me know if there is anything I need to change. Thanks
=> Screenshots of platform added

tool.css
This is the CSS for loader animation
=> css for loader

tool.html
loader added for all conversions
=> Add loader for file conversion.

client.js, server.js
See this - https://en.wikipedia.org/wiki/HATEOAS to know more about HATEOAS principle. Our application is not pure REST API-based, but we might migrate in the future to follow valid RESTful programming, which recommends to use HATEOAS to de-couple client and server as one its core principle.
=> Use HATEOAS principle while doing real-time entropy analysis polling.

src/client/app/components/alpha-diversity-computation/alpha-diversity-computation-controller.js, src/client/app/components/download-metasub-data/download-metasub-data-controller.js, src/client/app/components/entropy-analysis/entropy-analysis-component.js, src/client/app/components/entropy-analysis/entropy-analysis-controller.js, src/client/app/components/fasta-to-fastq-conversion/fasta-to-fastq-conversion-component.js, src/client/app/components/fastq-to-fasta-conversion/fastq-to-fasta-conversion-component.js
This is done since the native `window` object is global and exposes several test-ability problems as mentioned in - https://docs.angularjs.org/api/ng/service/$window (See **Overview** section).
=> Replace Vanilla JS's global 'window' object with AngularJS's $window service through Dependency Injection.

src/client/app/components/alpha-diversity-computation/alpha-diversity-computation.html, src/client/index.css
See - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u for more.
=> Replace the deprecated underline with the supported one.

README.md
Do have a look at it . And let me know if it is correct. I will be making changes if required..
=> Small error corrected
